package test;

import java.sql.SQLException;

public class DataBaseTest {

	public static void main(String[] args) throws SQLException {
		tools.AuthTools.userExists("3670163");

	}

}
